name: Vercel Preview Deploy

on:
  push:
    branches:
      - staging

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 18
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Vercel Preview Deploy
        uses: amondnet/vercel-action@v42.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod=false'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
